### ISSUE TITLE
Upgrade to Electron 1.8.2 release

### ISSUE THREAD

**Issue by yzgyyang** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#11]
Electron 1.8.2 stable has been released. https://electronjs.org/releases#1.8.2

**Comment by prash-wghats** [comment]
done!.(https://github.com/prash-wghats/Electron-VSCode-Atom-For-FreeBSD/tree/electron_v1.8.2)

**Comment by yzgyyang** [comment]
The same error "Cannot open /usr/ports/Mk/Uses/execinfo.mk" as described in #2 shown, I guess this is because execinfo was not removed in older version of Chrome. Also, is there a reason to switch to older version of Chromium (Chromium v59.0.3071.115, instead of 61.0.3163.100)?

**Comment by prash-wghats** [comment]
That's the version being used by electron v1.8.2. It wont compile with libcc v61.0.3163.100.

**Comment by yzgyyang** [comment]
@prash-wghats 

Next error when building libcc:
```
[3752/19005] CXX obj/third_party/angle/translator/blocklayout.o
FAILED: obj/third_party/angle/translator/blocklayout.o
clang++40 -MMD -MF obj/third_party/angle/translator/blocklayout.o.d -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DV8_DEPRECATION_WARNINGS -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=\"299960-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGL_GLEXT_PROTOTYPES -DEGL_EGLEXT_PROTOTYPES -I../../third_party/angle/include -I../../third_party/angle/src -I../../third_party/angle/include -I../../third_party/angle/src/common/third_party/numerics -Igen/angle -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -fcolor-diagnostics -m64 -march=x86-64 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-user-defined-warnings -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../third_party/angle/src/compiler/translator/blocklayout.cpp -o obj/third_party/angle/translator/blocklayout.o
In file included from ../../third_party/angle/src/compiler/translator/blocklayout.cpp:13:
In file included from ../../third_party/angle/src/common/utilities.h:12:
In file included from ../../third_party/angle/include/EGL/egl.h:39:
../../third_party/angle/include/EGL/eglplatform.h:111:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 76, in <module>
    sys.exit(main())
  File "script/build", line 53, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'src/out-x64/static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
```

I guess this is because of some error of CPP Flags?

**Comment by prash-wghats** [comment]
yes. Since i tested it in 11.0, i missed this. Replace `line 157` in `libchromiumcontent_111.diff` with this line:
`+	  args += ' use_sndio=false is_debug=false symbol_level=0 remove_webcore_debug_symbols=true extra_cxxflags="-I/usr/local/include"'`

**Comment by yzgyyang** [comment]
Great! Solved.
