### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-C', 'src/out-x64/static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by nkhine** [prash-wghats/Electron-VSCode-Atom-For-FreeBSD#4]
Hello,
I am trying to build VSCode on FreeBSD11.1, but get this:

```
Patching file ui/gfx/BUILD.gn using Plan A...
Hunk #1 succeeded at 22.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- a/third_party/angle/BUILD.gn       2017-11-25 15:25:36.291113000 +0400
|+++ b/third_party/angle/BUILD.gn       2017-11-25 16:08:18.478818000 +0400
--------------------------
Patching file third_party/angle/BUILD.gn using Plan A...
Hunk #1 succeeded at 421.
Hunk #2 succeeded at 474 with fuzz 1.
done
+ script/update -t x64
Warning: No "*.patch" files found in the "/usr/home/khine/Sandboxes/Electron-VSCode-Atom-For-FreeBSD/vscode/libchromiumcontent/patches/third_party" folder.
Done. Made 4659 targets from 1136 files in 3155ms
Done. Made 4620 targets from 1135 files in 2939ms
Done. Made 4642 targets from 1135 files in 3240ms
+ script/build --no_shared_library -t x64
ninja: Entering directory `src/out-x64/static_library'
[20/18382] CXX obj/base/third_party/symbolize/symbolize/demangle.o
FAILED: obj/base/third_party/symbolize/symbolize/demangle.o 
clang++40 -MMD -MF obj/base/third_party/symbolize/symbolize/demangle.o.d -DV8_DEPRECATION_WARNINGS -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=\"296320-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -fcolor-diagnostics -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -Wno-deprecated -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -I/usr/local/include -c ../../base/third_party/symbolize/demangle.cc -o obj/base/third_party/symbolize/symbolize/demangle.o
In file included from ../../base/third_party/symbolize/demangle.cc:37:
In file included from /usr/include/c++/v1/stdio.h:102:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
[25/18382] CXX obj/base/third_party/symbolize/symbolize/symbolize.o
FAILED: obj/base/third_party/symbolize/symbolize/symbolize.o 
clang++40 -MMD -MF obj/base/third_party/symbolize/symbolize/symbolize.o.d -DV8_DEPRECATION_WARNINGS -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=\"296320-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -fcolor-diagnostics -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -Wno-deprecated -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -I/usr/local/include -c ../../base/third_party/symbolize/symbolize.cc -o obj/base/third_party/symbolize/symbolize/symbolize.o
In file included from ../../base/third_party/symbolize/symbolize.cc:55:
In file included from ../../base/third_party/symbolize/utilities.h:5:
In file included from /usr/include/c++/v1/inttypes.h:234:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "script/build", line 62, in <module>
    sys.exit(main())
  File "script/build", line 46, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'src/out-x64/static_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
 ```

I had to manually install, the following requirements, as i was getting permission errors to /usr/ports/xxx/work directory

```
    97  13:41   ls /usr/ports/devel/gperf/
    98  13:41   pkg install devel/gperf
    99  13:42   pkg install devel/yasm
   100  13:43   pkg install sysutils/flock
   101  13:44   pkg install misc/usbids
   102  13:45   pkg install devel/py-Jinja2
   103  13:46   pkg install devel/py-ply
   104  13:46   pkg install www/py-html5lib
   105  13:47   pkg install devel/bison
   106  13:48   pkg install devel/ninja
```

this is on:

```
# uname -a
FreeBSD dhegdheer 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

running the command from terminal, i get:

```
ninja -C src/out-x64/static_library chromiumcontent:chromiumcontent
ninja: Entering directory `src/out-x64/static_library'
[2/18359] CXX obj/base/third_party/symbolize/symbolize/demangle.o
FAILED: obj/base/third_party/symbolize/symbolize/demangle.o 
clang++40 -MMD -MF obj/base/third_party/symbolize/symbolize/demangle.o.d -DV8_DEPRECATION_WARNINGS -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=\"296320-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -fcolor-diagnostics -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -Wno-deprecated -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -I/usr/local/include -c ../../base/third_party/symbolize/demangle.cc -o obj/base/third_party/symbolize/symbolize/demangle.o
In file included from ../../base/third_party/symbolize/demangle.cc:37:
In file included from /usr/include/c++/v1/stdio.h:102:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
[6/18359] CXX obj/base/third_party/symbolize/symbolize/symbolize.o
FAILED: obj/base/third_party/symbolize/symbolize/symbolize.o 
clang++40 -MMD -MF obj/base/third_party/symbolize/symbolize/symbolize.o.d -DV8_DEPRECATION_WARNINGS -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DCR_CLANG_REVISION=\"296320-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -fcolor-diagnostics -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -g0 -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -Wno-deprecated -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -I/usr/local/include -c ../../base/third_party/symbolize/symbolize.cc -o obj/base/third_party/symbolize/symbolize/symbolize.o
In file included from ../../base/third_party/symbolize/symbolize.cc:55:
In file included from ../../base/third_party/symbolize/utilities.h:5:
In file included from /usr/include/c++/v1/inttypes.h:234:
/usr/include/c++/v1/__config:73:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported.        use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
[7/18359] CC obj/base/third_party/xdg_mime/xdg_mime/xdgmimecache.o
ninja: build stopped: subcommand failed.
```

any advice is much appreciated

**Comment by prash-wghats** [comment]
remove `-D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR` from `extra_cxxflags="-D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -I/usr/local/include"'` in `libchromiumcontent.diff` and from `+          ' -I/usr/local/include -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -fno-rtti  -pthread -std=c++11 -fPIC',` in `electronv3.diff .In latest FreeBSD this flag is not required.
